### ISSUE TITLE
504 Server Error: GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by tonetto** [IUNetSci/botometer-python#11]
I have been observing some strange behavior from the API today and thought it was a problem on my side, but just now I got a 504 Server Error: GATEWAY_TIMEOUT. Is the API server going through some maintenance now is there any way I can debug this problem?

Thanks much!

**Comment by clayadavis** [comment]
There weren't any outages planned for today, but that doesn't mean there weren't any :smile:  A 504 is probably server-side and not something you're doing. I'm not seeing this behavior right now so it's hard for me to diagnose. If you see this happen again with the API, try the website. If the website also doesn't work, that's more evidence for capacity problems or other server issues.

**Comment by tonetto** [comment]
Thanks for the feedback. The website works fine, but I have a list of profiles I'd like to check.
Just now I tried the API again and this time got a 500. It seems like mashape must be going through some maintenance or something.

**Comment by clayadavis** [comment]
Our lab has a few APIs behind Mashape and all of them received error reports yesterday from users, so signs indeed point to Mashape having issues. Are your issues resolved today?

**Comment by clayadavis** [comment]
I think the Mashape issues have been cleared up; we haven't heard of these errors happening recently. Please reopen if you're still having issues.

**Comment by clayadavis** [comment]
Added entry to [FAQ](https://github.com/IUNetSci/botometer-python/wiki/Troubleshooting-&-FAQ#504-gateway-timeout).
