### ISSUE TITLE
500 Server Error: Internal Server Error for url: https://osome-botometer.p.mashape.com/2/check_account

### ISSUE THREAD

**Issue by leokassio** [IUNetSci/botometer-python#12]
Hi,

recently I am getting the following error during batch operations using `check_accounts_in`:

`500 Server Error: Internal Server Error for url: https://osome-botometer.p.mashape.com/2/check_account`

I was trying to figure it, but no success.

**Comment by clayadavis** [comment]
Does this error always occur? Can you try `check_accounts_in` with a subset of your data?

500 errors are usually due to the payload being the wrong "shape" or something in the payload being of type different than what is expected.

**Comment by leokassio** [comment]
I tried with small sets and still happening. 
I decided to migrate to individual check_account and get a chance to catch the exception and wait until  keep going.

**Comment by clayadavis** [comment]
Interesting. Sorry I'm not much help, there's not a lot to go on yet. If you can reproduce this error with a self-contained [gist](https://gist.github.com/), I could help diagnose the problem.

In any case, please keep us updated with your findings so I can hopefully fix this issue.

**Comment by clayadavis** [comment]
I think I can reproduce the issue you're seeing. For now if you get a 500 error, retry the request.

**Comment by leokassio** [comment]
Thank you Davis, I am doing it for now, but I have to wait some secs before retry.

**Comment by clayadavis** [comment]
I'm working on [version 1.1](https://github.com/IUNetSci/botometer-python/tree/1.1) that adds this wait & retry logic to `check_accounts_in`. Feel free to install the new version from the branch or else wait a week or so for the new release.

I'm going to leave this issue open until the 1.1 release.
