### ISSUE TITLE
Variance between data returned by API & returned by Botometer browser client 

### ISSUE THREAD

**Issue by RedactedCode** [IUNetSci/botometer-python#14]
The following are the (anonymised) data returned for a user by the Botometer Python API, using the sample code provided in the README:

>{'scores': {'universal': 0.22, 'english': 0.19}, 'user': {'id_str': '135791113', 'screen_name':      
>'abcdefg'}, 'categories': {'network': 0.15, 'content': 0.31, 'temporal': 0.16, 'sentiment': 0.43, 'friend': 0.3, 'user': 0.14}}

The following are the (anonymised) data returned from the Botometer browser client, using the "download data" option:
>[
>  {
>    "user": {
>      "screen_name": "abcdefg",
>      "id_str": "135791113",
>      "lang": "en-gb"
>    },
>    "categories": {
>      "content": 0.29,
>      "friend": 0.26,
>      "network": 0.14,
>      "sentiment": 0.44,
>      "temporal": 0.13,
>      "user": 0.15
>    },
>    "score": 0.22,
>    "scores": {
>      "english": 0.22,
>      "universal": 0.21
>    }
>  }
>]

These were created within a minute of each other.

Note that the downloaded JSON contains two extra elements:
 "lang" in the user section, and
 "score" at the same level as "user","categories" and "scores"

Note also that the values of nearly all elements are at slight variance between the two methods. Possibly not enough to be grossly misleading but nevertheless not insignificant.

**Comment by clayadavis** [comment]
I'll have to investigate the variance in the numbers, but the extra fields are there on purpose.

The extra "score" is the number displayed next to the gauge in the website results. This will be the same as one of the english or universal scores. It chooses which of those two scores to display based on the user's language, which is why this is also reported.

**Comment by clayadavis** [comment]
I believe this variance to be inherent in the classifier we use. Try classifying an account on the website (or API), waiting a minute, then trying again with the same source. The scores will probably be a bit different. Such is life with probabilistic methods. This underscores the folly in establishing a hard bot/not-bot cutoff threshold as discussed in the website [FAQ](https://botometer.iuni.iu.edu/#!/faq#bot-threshold).
