### ISSUE TITLE
Version 2 feature requests

### ISSUE THREAD

**Issue by clayadavis** [IUNetSci/botometer-python#18]
Now that the paid API is released, it's about time for some work on this, our official Python API implementation. Share with us anything you'd like to see included!

The most important focus for version 2 at this moment is to enable better error handling for bulk workloads.

**Comment by clayadavis** [comment]
Allow specifying screen_name or user_id kwargs

**Comment by clayadavis** [comment]
Better error messages for 401 and 404 errors, as in #21.

**Comment by phui** [comment]
part of error handling: in current version it is not clear what error the code should catch. After some discussion `botometer.TweepError` and `botometer.NoTimelineError` should be catch for batch job iterations. Catching the errors allows post-processing the problematic users without disrupting the long-running job. 

Suggestions are either to have a parent type that wraps these two kinds of exception, or to have the docs talking about what error to catch in a long running code.

**Comment by filmenczer** [comment]
We do not have resources to deal with these improvements, so closing issue for time being.
