### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by justinlittman** [IUNetSci/botometer-python#20]
Steps to reproduce:
```
curl -X POST --include 'https://osome-botometer.p.mashape.com/2/check_account'   -H 'X-Mashape-Key: mSXhy96RQmmshCpHVswh4bZis3nzp1Q1v6mjsnoyDK4jFVc1ki'   -H 'Content-Type: application/json'   -H 'Accept: application/json'   --data-binary '@data.json'
```
or:

```
    headers = {
        'X-Mashape-Key': MASHAPE_KEY
    }
    resp = requests.post('https://osome-botometer.p.mashape.com/2/check_account', json=data, headers=headers)
    resp.raise_for_status()
```

Result:
```
HTTP/1.1 100 Continue

HTTP/1.1 500 INTERNAL SERVER ERROR
Content-Type: text/html; charset=UTF-8
Date: Fri, 29 Dec 2017 21:02:47 GMT
Server: Mashape/5.0.6
Vary: Accept-Encoding,User-Agent
X-RateLimit-requests-Limit: 17280
X-RateLimit-requests-Remaining: 17270
Content-Length: 291
Connection: keep-alive

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

Note that these were tweets that were extracted from an existing dataset that was collected from the Twitter stream API. I can successfully call check_account for the same account using botometer-python.

I know this is the repo for botomoter-python, not botometer. If I should report elsewhere, please let me know. Thanks in advance for your assistance.
[data.json.zip](https://github.com/IUNetSci/botometer-python/files/1593879/data.json.zip)

**Comment by clayadavis** [comment]
Hi Justin,

Thanks for the issue. This is more an issue of the API, not the botometer-python library. So have a look at the [Mashape API documentation](https://market.mashape.com/OSoMe/botometer/overview) and see if that helps. If you're still having issues, create an issue on Mashape and/or send me another email.

Thanks,
CAD

**Comment by justinlittman** [comment]
Thanks @clayadavis. Sending you an email directly.
