### ISSUE TITLE
https://botometer.iuni.iu.edu/ doesn't show up in Firefox at all

### ISSUE THREAD

**Issue by SkyLeach** [IUNetSci/botometer-python#24]
![screen shot 2018-05-25 at 2 40 49 pm](https://user-images.githubusercontent.com/940228/40561013-a98d4272-6029-11e8-994f-766a115c43dc.png)

**Comment by clayadavis** [comment]
I use Firefox in development, so it definitely works with some versions of FF. If you press F12, click on the console, and refresh the site, do you see any errors?

**Comment by SkyLeach** [comment]
![screen shot 2018-05-26 at 9 51 56 am](https://user-images.githubusercontent.com/940228/40576861-1dd8e48c-60cb-11e8-8489-74c311fcbee5.png)

I checked and it does appear to work in the standard version just not in the dev edition.

**Comment by clayadavis** [comment]
Hmm, this is useful feedback. Thanks for noting your browser version. It'll probably take some time for me to investigate.

**Comment by clayadavis** [comment]
There's an exception that looks like it's coming from Angular. If you wouldn't mind pasting that into a gist or pastebin or whatever, it might help me troubleshoot.

**Comment by clayadavis** [comment]
I'm unable to reproduce using FF 61.0b9, so I definitely need that error message you're getting.

**Comment by SkyLeach** [comment]
placeholder... I have a deadline at work but I'll grab that error really quick and edit it into this comment.

**Comment by clayadavis** [comment]
It's possible the long red error is a red herring and the first, yellow warning is the real issue. Does the site load if you turn off your adblocker? I wonder if your adblock rules are blocking our `twitter-module` from being loaded, which in turn causes the red error.

**Comment by SkyLeach** [comment]
Yeah, seems to have been ABP.  Not 100% sure why though?  The domain should be allowed via CSP and I don't quite know why ABP would blacklist it.

Important to note: As a security analyst I NEVER disable my adblocker for any sites.  There are enough additional people using adblock that it's having a serious impact.  If this is being blocked it might be useful to find out why and what you can do to avoid the problem.

**Comment by clayadavis** [comment]
We work hard to make sure our stuff works with adblockers, Privacy Badger, etc. This is the first I've heard of this. I wonder if your ABP rules include a wildcard entry blocking anything with the word twitter in it?

Our `twitter-module` is pretty crucial to the operation of the site, it's definitely not optional.

**Comment by SkyLeach** [comment]
I can say that I haven't ever changed the default settings in my general-use browser for adblocker.  If I started doing that, I'd have to dedicate too much time to figuring out why anything doesn't work.  🤔

With that said, however, I'll have to double check but I'm pretty sure the reason was the host, not the resource.  I do know I use twitter services of many kinds regularly.  GDPR has, however, caused mozilla to change some of the CSP settings: [Mozilla Blog on GDPR and CSP changes](https://blog.mozilla.org/blog/2018/05/23/ready-for-gdpr-firefox-focus-offers-additional-tracking-protection-against-advertisers/)

I'll come back and update this when I get a chance to list the exact ABP violation errors (there were two, but I'm not able to open it right now).

**Comment by clayadavis** [comment]
That would help a lot. I wouldn't usually ask a user like you to do so much work here, but you're "lucky" enough to have both a working and non-working config :upside_down_face:

> With that said, however, I'll have to double check but I'm pretty sure the reason was the host, not the resource.

The `twitter-module.js` file is our code, statically-hosted on our servers, just like all the rest of our Javascript. Other resources like GA and Twitter Widgets being blocked shouldn't present a problem; one of my test configs does block those scripts and things work basically fine.

**Comment by SkyLeach** [comment]
So... this is the one I allowed through ABP:

`@@||botometer.iuni.iu.edu/components/twitter/twitter-module.0140831b9a.js`

I don't really know any more than that 🍺

I would investigate further but I honestly have too much other stuff on my plate right now and too little time for what I have to do let alone what I would like to do.  😜

**Comment by clayadavis** [comment]
It must then be blocking the word twitter then. We might consider renaming it in the future. Thanks for the bug report!
