### ISSUE TITLE
lib giving an error

### ISSUE THREAD

**Issue by jamarijohns** [IUNetSci/botometer-python#25]
Kindly assist with the below error when i try to execute the script ...  

bom = botometer.Botometer
AttributeError: module 'botometer' has no attribute 'Botometer'

**Comment by clayadavis** [comment]
You probably named your script `botometer.py` and it's trying to import itself.

**Comment by jamarijohns** [comment]
Thanks that was the issue

**Comment by clayadavis** [comment]
Thanks for the follow-up. This has been added to [Troubleshooting & FAQ](https://github.com/IUNetSci/botometer-python/wiki/Troubleshooting-&-FAQ#attributeerror-module-botometer-has-no-attribute-botometer).
