### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by thetoubi** [IUNetSci/botometer-python#26]
Currently, I cannot retrieve any results. Using the Python API, I encountered the error 502 (HTTPError: 502 Server Error: Bad Gateway for url: https://osome-botometer.p.mashape.com/2/check_account). Using the website, I also receive the same error (bad gateway or bad proxy). Testing my mashape keys, it produced the same error saying:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/api/2/check_account">POST&nbsp;/api/2/check_account</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

I used different laptops, different OS, and different keys/tokens (Twitter/mashape).

**Comment by clayadavis** [comment]
Thanks for the report. This was due to some server downtime we experienced
yesterday. Mashape acts as a proxy for requests, aid it couldn't forward
them because our server was down for a couple hours. Everything is back to
normal now.

**Comment by clayadavis** [comment]
Thanks for the report. This was due to some server downtime we experienced yesterday. Mashape acts as a proxy for requests, aid it couldn't forward them because our server was down for a couple hours. Everything is back to normal now.
