### ISSUE TITLE
Using the Pro API: "omit access token and access token secret"

### ISSUE THREAD

**Issue by thetoubi** [IUNetSci/botometer-python#27]
This might be a beginner's issue, sorry about that:

To make full use of the Pro API I followed the guide on this wiki page (https://github.com/IUNetSci/botometer-python/wiki/Using-the-Pro-API). Yet, when I omit the 'access_token' and 'access_token_secret' in the Botometer constructor, I receive the following error for the last line of code: 

```
Traceback (most recent call last):

  File "<ipython-input-2-16cf1b0c8b83>", line 15, in <module>
    **twitter_app_auth)

TypeError: __init__() missing 2 required positional arguments: 'access_token' and 'access_token_secret'"

```

Any ideas?

The code I use: 

```
import botometer
twitter_app_auth = {
    'consumer_key': 'XX',
    'consumer_secret': 'XX',
}

botometer_api_url = 'https://botometer-pro.p.mashape.com'

bom = botometer.Botometer(botometer_api_url=botometer_api_url,
                          mashape_key='XX',
                          **twitter_app_auth)
```

**Comment by clayadavis** [comment]
You are probably using an old version of the library. Update to 1.3 or above and you should be good to go.

**Comment by thetoubi** [comment]
Indeed, I did not use the current version. Yet, even after I updated the botometer module, the same error occurs. 

However, it runs when I use empty 'access_tokens' and 'access_tokens_secret':

``
import botometer
twitter_app_auth = {
    'consumer_key': 'XX',
    'consumer_secret': 'XX',
    'access_token': '',
    'access_token_secret':'',
}

botometer_api_url = 'https://botometer-pro.p.mashape.com'
mashape_key = 'XX'

bom = botometer.Botometer(botometer_api_url=botometer_api_url,
                          mashape_key=mashape_key,
                          **twitter_app_auth)

``

 But then it uses the free version of Botometer again, right?

**Comment by clayadavis** [comment]
You're correct that if you specify `access_token` and `access_token_secret` that it will continue to use user authentication, with its lower rate limits.

botometer 1.3 does not require these to be specified; the change was made with [this pull request](https://github.com/IUNetSci/botometer-python/commit/61deef80bc75bf834b7708b2a2d03f3e2cb3429d) and is the one feature added by v1.3. If you're getting this error, I might suspect that you may have multiple versions of the module installed and you may be using an older one. If you updated to 1.3 and have a notebook or something you've been using today, maybe you just need to restart the kernel and import the new version?

**Comment by thetoubi** [comment]
You were right. I had two versions of the module installed. As soon as I got rid of the old one, the code worked!

**Comment by clayadavis** [comment]
Thanks for the follow-up and glad to see it works for you :+1:
