### ISSUE TITLE
NoTimelineError

### ISSUE THREAD

**Issue by kurtawirth** [IUNetSci/botometer-python#28]
I am often running into an error where BotOMeter must be checking the followers of a user (or something else?) and is returning an error (see below) if that user has not tweeted rather than skipping that user and moving on. To be clear, this user is not the one being searched. How might I avoid this sort of problem in the future?

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  NoTimelineError: user '{'id_str': '557225288', 'screen_name': 'luanods'}' has no tweets in timeline`

**Comment by clayadavis** [comment]
Yes, Botometer returns an error when a user has no tweets in their timeline. This is done specifically to force those who are storing results to do something different when there are no tweets in the timeline, as Botometer doesn't return a score for those accounts. You can use a try/except to catch this error, store whatever you need to, and move on.

**Comment by clayadavis** [comment]
I added extra details to the [Troubleshooting & FAQ](https://github.com/IUNetSci/botometer-python/wiki/Troubleshooting-&-FAQ) wiki page.
