### ISSUE TITLE
Documentation of X-Mashape-Key is outdated

### ISSUE THREAD

**Issue by TamaraHager** [IUNetSci/botometer-python#31]
I think the documentation of the x-mashaped-key is outdated and the key has a new name X-RapidAPI-Key.

I clicked on the hyperlink of the mashaped marketplace and got redirected to the website RapidAPI. I still could find the botometer api on that marketplace but not the mentioned x-mashaped-key. 
Therefore I tried to use the X-RapidAPI-Key and it worked. That's why I think, they changed the name of the key.

**Comment by clayadavis** [comment]
Thanks for the heads up. I'll update the documentation soon.

**Comment by clayadavis** [comment]
The documentation is up to date, but I still need to update the `mashape_key` keyword in the module.
