### ISSUE TITLE
Threshold for determining Bot

### ISSUE THREAD

**Issue by sjgiorgi** [IUNetSci/botometer-python#35]
Is there a standard threshold for determining whether an account is a bot, assuming the returned scores are probabilities? 

Which score is commonly used?

**Comment by clayadavis** [comment]
The `cap` scores are probabilities, the "raw" scores aren't. As far as a standard threshold, each individual needs to choose a threshold that works for them depending on their tolerance for false positive/negative results.

**Comment by clayadavis** [comment]
Use the CAP scores. The raw scores are there mostly for backwards-compatibility.

**Comment by sjgiorgi** [comment]
What is the different between `english` and `universal`? Is one preferred over the other?

**Comment by clayadavis** [comment]
`english` uses all of the features, while `universal` omits the content and sentiment features. Use `english` if you're sure your content is English-language, `universal` otherwise.
