### ISSUE TITLE
Error: invalid syntax

### ISSUE THREAD

**Issue by CubicrootXYZ** [IUNetSci/botometer-python#36]
I am just trying to run the sample code, but it throws an error
`File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax`

I'm running it with Python 3.7

**Comment by phui** [comment]
This is a compatibility issue of `Tweepy` with `Python 3.7`. It is being addressed at https://github.com/tweepy/tweepy/issues/1017
