### ISSUE TITLE
Can I use the same twitter app authorization with multiple botometer api keys?

### ISSUE THREAD

**Issue by abaheti95** [IUNetSci/botometer-python#37]
I have to collect data for huge number of users and therefore I purchased multiple botometer pro accounts. I was wondering can I use the same twitter app authorization key with those multiple pro accounts. Will this in any way reduce the speed at which botometer will extract data for me?

**Comment by clayadavis** [comment]
Technically yes, you can use multiple pro accounts. However, Botometer's rate limits reflect those of the underlying Twitter API rate limits, so it may not help you unless you have elevated access from Twitter.
