### ISSUE TITLE
can you please update the wiki documentations (and HTTPError with a pro-api key)?

### ISSUE THREAD

**Issue by opendatasurgeon** [IUNetSci/botometer-python#44]
I have a pro-api key fpr botometer but I am keep getting:
`raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://osome-botometer.p.rapidapi.com/2/check_account`

I followed the example on the readme.md :( And the wiki pages have old info too. Thank you!

**Comment by opendatasurgeon** [comment]
This problem occurred due to old documentation. Please update the changes on your wikipages so it's easier for the people.

**Comment by mashabelyi** [comment]
@opendatasurgeon I am following the documentation in README and I get the same error. How did you manage to fix it?
