### ISSUE TITLE
Can you please update the wiki documentations with changes(Using the Pro API)?

### ISSUE THREAD

**Issue by opendatasurgeon** [IUNetSci/botometer-python#45]
Hello, your wiki pages talking about pro key contain wrong information:

it should be:

`botometer_api_url = 'https://botometer-pro.p.rapidapi.com'` 
            
`bom = botometer.Botometer(botometer_api_url=botometer_api_url,
                          wait_on_ratelimit=True,
                          rapidapi_key=rapidapi_key,
                          **twitter_app_auth)`

Rest of the process is same. Thank you!

**Comment by E-WOLF** [comment]
Thank you!

**Comment by yangkcatiu** [comment]
Just did, than you for the reminder.

We will soon change the default URL to `https://botometer-pro.p.rapidapi.com`, so extract configuration will no longer be needed.
