### ISSUE TITLE
How's the server situation now? Processing through Pro-api is slow.

### ISSUE THREAD

**Issue by opendatasurgeon** [IUNetSci/botometer-python#47]
Hi, I have a .csv file containing 17200 usernames (and one for loop that iterates through those usernames and gets the bot score). I have Pro key but it took more than a day just to process little over 3000 accounts?

 I am doing as per pro-api documentation:
```
# Pro API endpoint
botometerapiurl = 'https://botometer-pro.p.rapidapi.com'

# make a method of botometer
bom = botometer.Botometer(botometerapiurl=botometerapiurl,
                     waitonratelimit=True,
                    rapidapikey=rapidapikey,
                    **twitterappauth)
```
I know your servers are under stress so is that the reason? I am using my institution's internet to do this task. I don't think IO is a culprit. Should `waitonratelimit` be False??

**Comment by filmenczer** [comment]
Account related questions should be posted on RapidAPI discussion. Will follow up there.

**Comment by opendatasurgeon** [comment]
Posted there. Thanks.
