### ISSUE TITLE
I got this error after updating my mac to Catalina

### ISSUE THREAD

**Issue by bongfury** [IUNetSci/botometer-python#55]
my full code is below:

import botometer
import tweepy

name_list = ['username']

mashape_key = "***" # now it's called rapidapi key
twitter_app_auth = {
    'consumer_key': '***',
    'consumer_secret': '****',
    'access_token': '***',
    'access_token_secret': '***',
  }

bom = botometer.Botometer(wait_on_ratelimit=True,
                          mashape_key=mashape_key,
                          **twitter_app_auth)

bot = []
# Check a single account by screen name

for name in name_list:
    try:
        result = bom.check_account(name)
        if result["cap"]["english"]>0.5:
            bot.append(name)
            print(name)
    except tweepy.TweepError as e1:
        pass
    except botometer.NoTimelineError as e2:
        pass

print(bot)

and I got this error:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='osome-botometer.p.mashape.com', port=443): Max retries exceeded with url: /2/check_account (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10b9da2e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

How can I solve this issue? This worked well before update.

**Comment by filmenczer** [comment]
Be sure to update to the latest version of botometer-python.
