### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by bitscott1102** [IUNetSci/botometer-python#56]
requests.exceptions.HTTPError: 404 Client Error: Not Found for URL: 
"Missing RapidAPI application key.

Is it because of the new version? What part of my code should I change?

**Comment by bitscott1102** [comment]
Also on the RapidAPI, it says I cannot access the endpoint. I cannot checking the account now.

**Comment by yangkcatiu** [comment]
It seems the Rapid API key is missing in your code.

Please be sure to
1. resubscribe to one of the new plans
2. upgrade the botometer-python package in your local environment
3. follow the readme closely
