### ISSUE TITLE
What is the daily quota of the ultra plan?

### ISSUE THREAD

**Issue by mavolin** [IUNetSci/botometer-python#61]
The readme of this repo states, that the Ultra plan allows up to 450 requests per 15-minute window, which would mean a daily quota of `450 * 4 * 24 = 43200`. However, the pricing section on the Rapid-API website states that daily requests are capped at 17280, but with no 15 min rate limit between requests.
Which of these quotas is correct, and is there in fact a 450 requests per 15 min rate limit?

**Comment by yangkcatiu** [comment]
The 15-minute window limit is imposed by Twitter. The 17280 daily quote is imposed by us. So both of them are correct and in effect.

However, the 17280 daily quote is a soft limit, you can go beyond it and query more by paying overage.
