### ISSUE TITLE
Questions about BotometerLite

### ISSUE THREAD

**Issue by ShawWang1991** [IUNetSci/botometer-python#62]
I purchased BotometerLite, it can return botscore, tweet_id and user_id. My problem is that my twitter data only has user_name but no user_id, and in BotometerLite batch analysis, accounts that have been cancelled will be automatically skipped, so I have no way to match the robot analysis result with user_name. How can I add user_name to the returned result?

**Comment by yangkcatiu** [comment]
Unfortunately it's not possible to get the scores for users that have been deleted/suspended.
