### ISSUE TITLE
tweepy.error.TweepError

### ISSUE THREAD

**Issue by JackandJammy** [IUNetSci/botometer-python#63]
Hello,I got a problem and failed to solve.

tweepy.error.TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?id=%40Hog8oy&include_rts=True&count=200 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019C10C500D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Till now ,none of accounts succeed , and the total number of test is below 400.

Thank you!

**Comment by yangkcatiu** [comment]
It seems you were unable to access "api.twitter.com". Please make sure you do have access to twitter.com.

**Comment by JackandJammy** [comment]
> It seems you were unable to access "api.twitter.com". Please make sure you do have access to twitter.com.

Yes,I can open twitter.com. But I failed to open  "api.twitter.com".

**Comment by yangkcatiu** [comment]
Could you try to use tweepy directly to fetch data from Twitter? It doesn't seem to be a problem with our package.

**Comment by yangkcatiu** [comment]
Close for now.
