### ISSUE TITLE
No module named 'tweepy.error'

### ISSUE THREAD

**Issue by qwerfdsaplking** [IUNetSci/botometer-python#65]
When I import botometer, I get the error: No module named 'tweepy.error'.  Could you please help me?

**Comment by clayadavis** [comment]
It sound like you need to install `tweepy`, as mentioned in the [dependencies](https://github.com/IUNetSci/botometer-python#dependencies) section of the `README`.

**Comment by shiwangsimba** [comment]
I also encountered this problem. I found out that some things were renamed after the Tweepy version was updated. For example: 'error' was renamed 'errors', so you need to use 'tweepy.errors', 'RateLimitError' was renamed 'TooManyRequests', 'TweepError' was renamed 'TweepyException', if you don't want to change the name, then reduce the version of Tweep to 3.10.0

**Comment by yangkcatiu** [comment]
Please see our FAQ: https://github.com/IUNetSci/botometer-python/wiki/Troubleshooting-&-FAQ
