### ISSUE TITLE
How do I set up a proxy?

### ISSUE THREAD

**Issue by shiwangsimba** [IUNetSci/botometer-python#66]
There is a problem with my network. I can open Twitter in Google, but the running code will report an error: TimeoutError: [WinError 10060]
![image](https://user-images.githubusercontent.com/65696505/135114031-118d6aae-fbe2-42e4-899f-705b87147c8b.png)

so I tried to use the proxy method. I added the parameter 'proxy' to tweepy.API
![image](https://user-images.githubusercontent.com/65696505/135114442-341b6a5c-0ef3-49be-beec-a13a915e3d41.png)

but it still reported another error:
![image](https://user-images.githubusercontent.com/65696505/135114340-67de938d-87eb-44d5-a21b-50b6593a2767.png)

**Comment by filmenczer** [comment]
This may be because Tweepy just released a new version 4.0.0 that is not backward compatible.

Until we can update botometer-python, you could try to install Tweepy v3.10.0 or an earlier version
