### ISSUE TITLE
TypeError: user_timeline() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by shiwangsimba** [IUNetSci/botometer-python#67]
![image](https://user-images.githubusercontent.com/65696505/135134776-6e56c5e6-8501-401d-9683-a19c6f31a217.png)

how to solve this problem

**Comment by shiwangsimba** [comment]
![image](https://user-images.githubusercontent.com/65696505/135134875-a4817d3f-1001-4337-92c8-089f78986eb2.png)

![image](https://user-images.githubusercontent.com/65696505/135134935-b977a4a8-08a5-4100-8f0d-8deff75d025c.png)

**Comment by filmenczer** [comment]
See https://github.com/IUNetSci/botometer-python/issues/66

**Comment by shiwangsimba** [comment]
Thank you, this problem is solved after lowering the version of tweepy, but a new problem appears:

![image](https://user-images.githubusercontent.com/65696505/135207603-451a17fe-ed1d-4047-b764-39804c4282b8.png)

**Comment by yangkcatiu** [comment]
It seems tweepy is having trouble accessing the Twitter API. I would recommend creating an issue in tweepy's repository.

**Comment by shiwangsimba** [comment]
Yes, they seem to be solving this problem, see https://github.com/tweepy/tweepy/issues/1606
