### ISSUE TITLE
Rate limit of "ultra" API access

### ISSUE THREAD

**Issue by JanaLasser** [IUNetSci/botometer-python#69]
I am trying to classify a large number (250k) accounts using the "ultra" subscription to the API. Since I need all sub-scores, I am not using the "lite" endpoint. 

I have tried to parallelize calls but API responses are very slow and stop occasionally, for some period of time. This looks to me like I have run into some hidden rate limit, even though the rate limit of "one request/second" should only apply to the "basic" subscription. Is there another rate limit that I should be aware of?

**Comment by filmenczer** [comment]
The average latency for the v4 endpoint is currently around 1.4 s. This includes communication between RapidAPI and our server, calculation of the 1k+ features, and classification. On top of that, the botometer-python library has to fetch the data from Twitter, therefore is also subject to the Twitter API rate limits. 

@yangkcatiu may be able to provide further details.

**Comment by JanaLasser** [comment]
Thanks for the quick reply! I think what I am observing might be due to the Twitter API rate limit then. 

If I understood correctly, I should be able to reduce the 1.4s latency of the v4 endpoint by parallelizing requests (given that I am not constrained by the Twitter API rate limit), correct?

**Comment by JanaLasser** [comment]
Thank you for the additional info! I will go ahead and ask RapidAPI about their internal constraints.
