### ISSUE TITLE
Checking bot account based on previous history of tweets

### ISSUE THREAD

**Issue by reachyou91** [IUNetSci/botometer-python#73]
Based on papers associated with Botometer, I realized that botometer score is made by several features of recent tweets and the activity of an account. Would there any way I can check the bot account based on previous tweets say in 2017?

**Comment by filmenczer** [comment]
In theory it is possible, but you need to have the data that you would have obtained if you had queried the Twitter API back in 2017, and you have to format that data in the way that the Botometer API expects it. (This library can provide guidance about data and formatting.)

Alternatively, if you just have single tweets containing user profiles, you could use the BotometerLite endpoint.

**Comment by reachyou91** [comment]
Thank you @filmenczer. I have obtained the tweet via Twitter API in 2017. I think that BotometerLite's non-Twitter mode does the work for this case. 
If I have multiple tweets from a user with the user profile in 2017, can't I use non-Twitter mode for bot status? or did you mean I only need one single tweet of each user as it utilizes only user profile features?  I wonder if the algorithm utilizes features from only user profile information or if it also utilizes tweets to generate a bot score.

**Comment by filmenczer** [comment]
That is correct. The endpoint only uses profile info extracted from the user object within the tweet object. So each tweet will give you one score. If you have multiple tweets from the same account, you will get multiple scores, which may or may not be different based on the profile data. HTH.
