### ISSUE TITLE
BotometerLite: put n users in the screen_name_list variable, but returns bot values of n-2 users

### ISSUE THREAD

**Issue by YaxinDai** [IUNetSci/botometer-python#76]
Hi! I am using the the BotometerLite endpoint to collect bot values of multiple users in bulk. Since the maximum user limit for BotometerLite is 100, I put the usernames of 100 users in the variable of screen_name_list; however, the program only returns 98 bot values. The bot values of No. 99 and No. 100 user were not calculated. I also tried other numbers, like inputing 94 and 51 usernames, then I got bot values of 92 and 49 users. When I lower the number of usernames to 10, I can get bot values for all these 10 users. 

Does anyone know why it happens? Thanks.

**Comment by yangkcatiu** [comment]
I'm guessing there are two accounts that are no longer available.

**Comment by YaxinDai** [comment]
Thanks very much for the replu and sorry for the stupid question. It is because the users that are suspended will not be returned with a note like the Botometer-V4.
