### ISSUE TITLE
Botometer Lite

### ISSUE THREAD

**Issue by Char1996** [IUNetSci/botometer-python#77]
I just bought the ultra plan for the api and as i read through the github it says tweets as inputs for botometerlite. 
Currently i have date, twitter id, content, username as my data. when i feed content to botometerlite it shows 400 Client Error: Bad Request for url: https://botometer-pro.p.rapidapi.com/litev1/check_accounts_in_bulk.

I am not sure what the quesiton is? is it about my data or the api is not working?

**Comment by Char1996** [comment]
![1671286057537](https://user-images.githubusercontent.com/120793644/208245960-0dc9818c-924d-47ec-a06e-e0e20b1080c3.jpg)

**Comment by Char1996** [comment]
and I am using the non-twitter version BTW. Thanks!

**Comment by filmenczer** [comment]
Please see the [API documentation](https://rapidapi.com/OSoMe/api/botometer-pro/details) on the format of the user objects to be passed to the endpoint. Each object should be the complete user object as received from the Twitter API.

**Comment by Char1996** [comment]
400 Client Error: Bad Request for url: https://botometer-pro.p.rapidapi.com/litev1/check_accounts_in_bulk
I am doing fine using the twitter version, but there are some issues with userid as well.
So I want to use the non twitter version because it shows the twitter id, and this errors shows up. The api key is correct.

**Comment by yangkcatiu** [comment]
@Char1996 it seems the payload has some format issues. It's impossible for us to diagnose without further information, unfortunately.
